name: PixelsPointsPolygons
size: ${..encoder.in_size}
in_path: /mnt/DATA/IMANE/AI4SmallFarms/sentinel-2-asia
out_path: /mnt/DATA/IMANE/AI4SmallFarms_output
annotation_type: fields
country: Asia

annotations:
  train: /mnt/DATA/IMANE/AI4SmallFarms/sentinel-2-asia/output_coco_32/train_coco.json
  val:   /mnt/DATA/IMANE/AI4SmallFarms/sentinel-2-asia/output_coco_32/val_coco.json
  test:  /mnt/DATA/IMANE/AI4SmallFarms/sentinel-2-asia/output_coco_32/test_coco.json

train_subset: ${...run_type.train_subset}
val_subset:   ${...run_type.val_subset}
test_subset:  ${...run_type.test_subset}
